/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_SimpDecoder */

#ifndef _Included_org_example_SimpDecoder
#define _Included_org_example_SimpDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_SimpDecoder
 * Method:    decode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_SimpDecoder_decode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
